server:
  port: 7575

spring:
  application:
    name: wigell-padel-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:wigelldb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: Europe/Stockholm
  h2:
    console:
      enabled: true
      path: /h2-console

wigell:
  pricing:
    base: 300.00
    extraPerPlayer: 50.00
    basePlayers: 2
  currency:
    apiplugin:
      baseUrl: https://v1.apiplugin.io
      apiKey: tR3Zmu2G
    failOpen: true

logging:
  level:
    root: INFO
  file:
    name: logs/wigell-padel-service.log

